name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches: 
      - "master" 
  pull_request:
    branches: 
      - "master" 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      name: Login no DockerHub
    - uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 

      name: Configura o OpenJDK 21
    - uses: actions/setup-java@v3
    
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'

    - name: Constrói o projeto
      working-directory: ./teste-project  
      run: mvn clean package -DskipTests
       
     
    