name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches: 
      - "master" 
  pull_request:
    branches: 
      - "master" 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      name: Login to DockerHub
    - uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 

      name: Setuo Amazon Corretto OpenJDK 21
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'

    - name: Build Project
      working-directory: ./teste-project  
      run: mvn clean package -DskipTests
    
    - name: Docker Compose Build
      working-directory: ./teste-github-actions
      run: docker-compose --build 
       
     
    